### ISSUE TITLE
FormatException (FormatException: Unexpected character (at character 1)

### ISSUE THREAD

**Issue by CanArslanDev** [faithoflifedev/google_vision_workspace#12]
Hello,
I added the service_credentials.json file to the assets and then ran the sample project, but I received this error.

 final googleVision = await GoogleVision.withJwt(jwtFromAsset);
 Exception has occurred.
FormatException (FormatException: Unexpected character (at character 1)
/data/user/0/com.example.vision_demo/cache/service_credentials.json
^

![image](https://github.com/faithoflifedev/google_vision/assets/76579053/3dcb468d-7c9e-470c-82bd-2362c58d4b0f)

**Comment by CanArslanDev** [comment]
my service_credentials.json file 

![image](https://github.com/faithoflifedev/google_vision/assets/76579053/016941cd-2ff6-4aa1-bd2c-0f76557b14e7)

**Comment by CanArslanDev** [comment]
I solved it this way, but this needs to be corrected in the sample project.

```
  void _processImage() async {
    final jwtFromAsset = await DefaultAssetBundle.of(context)
        .loadString("assets/service_credentials.json");
    final googleVision = await GoogleVision.withJwt(jwtFromAsset);
    
    //codes...
```

**Comment by faithoflifedev** [comment]
Hi @CanArslanDev, 

This code,
```dart
final googleVision = await GoogleVision.withJwt(jwtFromAsset);
```
will only work if `jwtFromAsset` is a string (as you later surmised).

The two signatures for authenticating with jwt are:

```dart
Future<GoogleVision> withJwt(String credentials,
      [String scope = 'https://www.googleapis.com/auth/cloud-platform'])

Future<GoogleVision> withJwtFile(String credentialsFileName,
      [String scope = 'https://www.googleapis.com/auth/cloud-platform'])
```

The package currently has no dependency on `Flutter` (so it can't references material or services code) since my original use case when writing it was automating image processing from a security camera through a cli app.  I've since seen that the majority of people using the package do so in `Flutter`, so if time permits, at some time in the future I may create a separate package specifically for Flutter.

**Comment by CanArslanDev** [comment]
Hello @faithoflifedev , yes, I understand that you did not do it specifically for Flutter, but doesn't the example project already work with Flutter? Then shouldn't you make this code for Flutter?
