### ISSUE TITLE
 DioException [bad response]: This exception was thrown because the response has a status code of 400 and RequestOptions.validateStatus was configured to throw for this status code.

### ISSUE THREAD

**Issue by CanArslanDev** [faithoflifedev/google_vision_workspace#20]
Hello, I have opened this issue before in [this issue](https://github.com/faithoflifedev/google_vision_workspace/issues/14), unfortunately I could not find a solution so I formatted my computer and it was solved. Now I encountered this problem again and I cannot solve it. I checked the api key, although it works on my other windows and mac devices, it does not work on a specific windows computer. What's different is that it was broken yesterday when I just turned off and turned on the computer while it was working. When I tested all the other APIs, I saw that they worked without any problems, so I do not think there is a problem with the internet. But I couldn't find the reason for this problem.

This code gives an error, I am 100% sure that the credentials are correct
```dart
final googleVision = await vision.GoogleVision.withJwt(jwtFromAsset)
```

Logs
```
I/flutter ( 6977): DioException [bad response]: This exception was thrown because the response has a status code of 400 and RequestOptions.validateStatus was configured to throw for this status code.
I/flutter ( 6977): The status code of 400 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
I/flutter ( 6977): Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
I/flutter ( 6977): In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.
I/Camera  ( 6977): refreshPreviewCaptureSession
```

Version

```yaml
google_vision: 1.2.1
```

OS: Windows 11

**Comment by faithoflifedev** [comment]
Hi @CanArslanDev,

I'm not sure you're aware, but as of about 5 months ago I published a [Flutter specific Google Vision Package](https://pub.dev/packages/google_vision_flutter).  It might be worth your while to migrate to this package.  Also, the latest releases of both the Dart and Flutter packages also support the use of an [API key](https://pub.dev/documentation/google_vision/latest/google_vision/GoogleVision/withApiKey.html) in place of the JSON credentials file, which might make things a bit easier for you.

In terms of the issue you mentioned above, I don't have a Windows 11 environment to test with and you haven't really provided enough information for me to recreate the issue.  Maybe try switching to the Flutter widget and see if the issue is resolved.

**Comment by rellyrell24** [comment]
I am getting this error. Not sure what's the issue exactly. 

I am using server pod to build my application. Here the endpoint that is causing the exception:

```
class VisionEndpoint extends Endpoint {
  Future<Map<String, dynamic>> detectText(
      Session session, String imageUri) async {
    final googleVision = await GoogleVision().withApiKey(
      apiKey,
      additionalHeaders: {
        'com.example.screenStudyProFlutter': 'X-Ios-Bundle-Identifier'
      },
    );
    final textDetectionResponse = await googleVision.image
        .documentTextDetection(JsonImage.fromGsUri(imageUri));
    if (textDetectionResponse == null) return {};
    return textDetectionResponse.toJson();
  }
}
```

Can someone shed some light on why I am getting this error? I was thinking I need some authentication headers for `dio`. If I need to create a new issue, I can do so. :)

**Comment by rellyrell24** [comment]
I changed to using packages `googleapis` and using `googleapis_auth` instead. The new error states that there is no billing account, so I guess that was my issue before.
